### ISSUE TITLE
Couldn't decrypt with that SSH key, please choose another one.

### ISSUE THREAD

**Issue by lucasliu2022** [FiloSottile/age#552] opened 2024-03-14 13:33 UTC
## Environment

* OS: mac os 
* age version: 14.3.1 (23D60)

## What happened

```
Couldn't decrypt with that SSH key, please choose another one.
Possible causes are:
You have specified the file which doesn't contain valid private key.
Your private key doesn't match your public key in GitHub. It could happen if you've changed local ssh key recently.
Internal ape error:
age: error: no identity matched any of the recipients
age: report unexpected or unhelpful errors at https://filippo.io/age/report
Enter path to the private SSH key to use or just press Enter to show existing keys: ^C
```

**Comment by alerque** [comment] 2024-03-14 13:48
Evidently a duplicate of #544, #545, #550, and #551. In other words **not an issue with this project**. See https://github.com/fluencelabs/dev-rewards/issues/19.

**Closed** 2024-03-14 14:23 UTC
