### ISSUE TITLE
Unsupported SSH key type: ecdsa-sha2-nistp256

### ISSUE THREAD

**Issue by kn1g** [FiloSottile/age#554] opened 2024-03-21 11:10 UTC
## Environment

* OS: Ubuntu docker image ubuntu:22.04
* age version: 1.0.0

## What were you trying to do

```
age --decrypt --identity /id_ecdsa --output dec.bin enc.bin
```

## What happened

```
age: error: reading "/id_ecdsa": unsupported SSH key type: ecdsa-sha2-nistp256
```

**Comment by FiloSottile** [comment] 2024-06-16 08:45
Duplicate of #142

**Closed by FiloSottile** 2024-06-16 08:45 UTC
