### ISSUE TITLE
UX: Can't intermix arguments and options

### ISSUE THREAD

**Issue by noncombatant** [FiloSottile/age#29] opened 2019-12-28 00:58 UTC
I keep getting this:

```
~/age/cmd/age % ./age -d blorp --output snort
Error: too many arguments.
age accepts a single optional argument for the input file.
[ Did age not do what you expected? Could an error be more useful? Tell us: https://filippo.io/age/report ]
~/age/cmd/age % ./age -d --output snort blorp 
... success
```

One way to handle this would be to make the input an option (`-i`, `--input`), and not have any arguments at all. (But see bug #30 about using arguments for subcommands.) That would be maximally consistent and clear.

**Comment by FiloSottile** [comment] 2019-12-28 01:39
Thanks for the report! This is a duplicate of #27, which really suggests we need to fix this. Unfortunately `-i` is taken by `--identity`, but I feel like we can make this better by accepting intermixed flags and args, or by detecting the issue and printing a better error.

**Closed by FiloSottile** 2019-12-28 01:39 UTC
Labels: UX report
