### ISSUE TITLE
UX: Require verification of keyed password when using -p switch at command line

### ISSUE THREAD

**Issue by unicorntoes** [FiloSottile/age#105] opened 2020-02-24 21:18 UTC
## What were you trying to do
Win32 - After entering the password prompt via -p switch, I was not able to verify I entered the correct password as age ran with the first password it was given. There is an opportunity to improve this behavior. 

## What happened
Age encrypted the file with the password keyed when prompted. Since there was no verification of the keyed password, I have no way of knowing if the password I entered was correct except to try to decrypt the file and test that the password keyed actually was keyed correctly. 
```
<insert terminal transcript here>
```

**Comment by FiloSottile** [comment] 2020-02-24 23:05
Duplicate of #39 which was fixed but not released. (I really need to make a release!)

**Closed by FiloSottile** 2020-02-24 23:05 UTC
Labels: UX report
