### ISSUE TITLE
I am the winner of the airdrop

### ISSUE THREAD

**Issue by lnsane** [FiloSottile/age#557] opened 2024-03-29 12:53 UTC
Will use SSH key to generate proof data. Press enter to proceed.

Couldn't decrypt with that SSH key, please choose another one.
Possible causes are:
You have specified the file which doesn't contain valid private key.
Your private key doesn't match your public key in GitHub. It could happen if you've changed local ssh key recently.
Internal ape error:
age: error: no identity matched any of the recipients
age: report unexpected or unhelpful errors at https://filippo.io/age/report

why？

That's why, I can't receive the reward? I really need and appreciate winning the prize, but why can’t I claim it? Please help me.

**Comment by lnsane** [comment] 2024-03-29 12:55
Really please, I really, really need it.

**Comment by alerque** [comment] 2024-03-29 12:56
This is a duplicate of #544, #545, #550, #551, and #552. In other words your issue is **not an issue with this project**. See https://github.com/fluencelabs/dev-rewards/issues/19.

**Closed** 2024-03-29 16:52 UTC
